### PR TITLE
Allow functions with Quantity x values

### PR DESCRIPTION
**Pull request by rafaqz**

### CODE REVIEW

**Comment by rafaqz** [comment]
I have no idea how to actually test this

**Comment by jw3126** [comment]
You could create a signature `recipe!(plotattributes, f, xs)` and test that method. But yeah it's not the greatest test and I am open to merge as is.

**Comment by jw3126** [comment]
@rafaqz should I merge or do you want to move the "heavy lifting" to `recipe!`?

**Comment by rafaqz** [comment]
Lol. probably just merge.

**Pull request merged**
