### PR TITLE
Support Unitful ticks

### PR DESCRIPTION
**Pull request by JeffFessler**
should address #55

Do you want a version bump as part of the PR?

### CODE REVIEW

**Comment by jw3126** [comment]
Thanks looks good! Can you add a ticks plot to the docs:
https://github.com/jw3126/UnitfulRecipes.jl/blob/master/docs/lit/examples/1_Examples.jl
> Do you want a version bump as part of the PR?

Sure, if you bump the version we can release immediately!

**Comment by briochemc** [comment]
Thanks! I agree with @jw3126 that an example would be nice. If you have a very small MWE (I would say 4 lines or less?) that looks nice that would be great! Maybe something with the `xticks=x[[1,end]]` like you mentioned in the linked issue?

**Comment by JeffFessler** [comment]
To keep it concise I modified the `lims` example to also illustrate `ticks` because they often are modified together.

**Comment by JeffFessler** [comment]
The codecov report says there is one new missed line.  I can't view the report it seems, but if you tell me which line is missed I can try to update the tests to cover it if it is related to this PR.

**Review by jw3126 — APPROVED** [review]
LGTM thanks again!

**Comment by jw3126** [comment]
> The codecov report says there is one new missed line. I can't view the report it seems, but if you tell me which line is missed I can try to update the tests to cover it if it is related to this PR.

I cannot view the report either, that is strange. Anyway I don't think this PR really decreases coverage in any way.

**Comment by briochemc** [comment]
LGTM too! For the record, here are the new examples:
Screen Shot 2021-06-18 at 10 25 59 am
Screen Shot 2021-06-18 at 10 26 12 am

**Review by briochemc — APPROVED** [review]

**Pull request merged**
